INDIAN_FOOD_DATASET = [
    # BREAKFAST ITEMS
    {
        "name": "Poha with Peanuts & Veggies",
        "name_hindi": "पोहा",
        "category": "breakfast",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl",
        "serving_weight_g": 200,
        "calories": 270,
        "protein_g": 6.5,
        "carbs_g": 45.0,
        "fat_g": 7.5,
        "fiber_g": 4.0,
        "approx_cost_inr": 35.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["flattened rice", "peanuts", "onion", "mustard seeds", "turmeric", "curry leaves"],
        "allergens": ["peanuts"],
        "glycemic_index": "Medium",
        "description": "Light flattened rice steamed with spices, crunchy peanuts, and fresh lemon."
    },
    {
        "name": "Vegetable Upma",
        "name_hindi": "उपमा",
        "category": "breakfast",
        "cuisine": "South Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl",
        "serving_weight_g": 200,
        "calories": 240,
        "protein_g": 5.8,
        "carbs_g": 42.0,
        "fat_g": 5.5,
        "fiber_g": 4.5,
        "approx_cost_inr": 30.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["semolina", "carrots", "peas", "mustard seeds", "ginger", "curry leaves"],
        "allergens": ["gluten"],
        "glycemic_index": "Medium",
        "description": "Nutritious roasted semolina dish tempered with South Indian spices and diced vegetables."
    },
    {
        "name": "Idli Sambar (2 Pcs)",
        "name_hindi": "इडली सांभर",
        "category": "breakfast",
        "cuisine": "South Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 plate (2 idlis + sambar)",
        "serving_weight_g": 250,
        "calories": 210,
        "protein_g": 8.0,
        "carbs_g": 40.0,
        "fat_g": 2.0,
        "fiber_g": 5.0,
        "approx_cost_inr": 45.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["fermented rice flour", "urad dal", "toor dal", "drumstick", "tamarind", "spices"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Steamed fermented rice cakes served with protein-rich lentils vegetable sambar."
    },
    {
        "name": "Masala Dosa with Coconut Chutney",
        "name_hindi": "मसाला डोसा",
        "category": "breakfast",
        "cuisine": "South Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 dosa",
        "serving_weight_g": 220,
        "calories": 330,
        "protein_g": 7.2,
        "carbs_g": 54.0,
        "fat_g": 9.5,
        "fiber_g": 4.0,
        "approx_cost_inr": 60.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["rice", "urad dal", "potato masala", "ghee", "coconut chutney"],
        "allergens": ["lactose"],
        "glycemic_index": "Medium",
        "description": "Crispy fermented crepe stuffed with spiced potato mash served with fresh coconut chutney."
    },
    {
        "name": "Moong Dal Chela (2 Pcs)",
        "name_hindi": "मूंग दाल चीला",
        "category": "breakfast",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "2 pancakes",
        "serving_weight_g": 180,
        "calories": 260,
        "protein_g": 14.5,
        "carbs_g": 36.0,
        "fat_g": 6.0,
        "fiber_g": 6.5,
        "approx_cost_inr": 40.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["yellow moong dal", "spinach", "coriander", "green chili", "cumin"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "High-protein savory green mung bean savory pancakes with fresh coriander and green chilies."
    },
    {
        "name": "Paneer Bhurji with Whole Wheat Toast",
        "name_hindi": "पनीर भुर्जी और टोस्ट",
        "category": "breakfast",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl bhurji + 2 bread slices",
        "serving_weight_g": 230,
        "calories": 390,
        "protein_g": 21.0,
        "carbs_g": 30.0,
        "fat_g": 22.0,
        "fiber_g": 4.5,
        "approx_cost_inr": 75.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["paneer", "whole wheat bread", "onion", "tomato", "butter", "turmeric"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Low",
        "description": "Scrambled cottage cheese cooked with onions, tomatoes, and aromatic Indian herbs."
    },
    {
        "name": "Egg Bhurji with Multigrain Toast",
        "name_hindi": "अंडा भुर्जी और टोस्ट",
        "category": "breakfast",
        "cuisine": "North Indian",
        "dietary_type": "eggetarian",
        "serving_unit": "2 eggs bhurji + 2 toasts",
        "serving_weight_g": 210,
        "calories": 340,
        "protein_g": 19.5,
        "carbs_g": 26.0,
        "fat_g": 17.0,
        "fiber_g": 3.8,
        "approx_cost_inr": 50.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["eggs", "multigrain bread", "onion", "green chilies", "olive oil"],
        "allergens": ["egg", "gluten"],
        "glycemic_index": "Low",
        "description": "Indian style spicy egg scramble served alongside fiber-rich toast."
    },
    {
        "name": "Oats Porridge with Almonds & Banana",
        "name_hindi": "ओट्स दलिया",
        "category": "breakfast",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl",
        "serving_weight_g": 250,
        "calories": 310,
        "protein_g": 11.0,
        "carbs_g": 48.0,
        "fat_g": 8.0,
        "fiber_g": 7.0,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["rolled oats", "milk", "banana", "almonds", "honey"],
        "allergens": ["lactose", "nuts"],
        "glycemic_index": "Low",
        "description": "Heart-healthy oats simmered in warm milk topped with potassium-dense banana and sliced almonds."
    },
    {
        "name": "Sprouted Moong Salad with Lemon",
        "name_hindi": "अंकुरित मूंग चाट",
        "category": "breakfast",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl",
        "serving_weight_g": 180,
        "calories": 180,
        "protein_g": 12.5,
        "carbs_g": 28.0,
        "fat_g": 1.5,
        "fiber_g": 8.0,
        "approx_cost_inr": 25.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["sprouted moong", "cucumber", "pomegranate", "lemon juice", "chaat masala"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Enzyme-rich raw sprouted mung bean chat loaded with vitamin C and plant fiber."
    },
    {
        "name": "Aloo Paratha with Curd",
        "name_hindi": "आलू पराठा और दही",
        "category": "breakfast",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 paratha + 1/2 cup curd",
        "serving_weight_g": 240,
        "calories": 380,
        "protein_g": 9.5,
        "carbs_g": 52.0,
        "fat_g": 15.0,
        "fiber_g": 5.0,
        "approx_cost_inr": 40.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["whole wheat flour", "spiced mashed potato", "ghee", "fresh curd"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Medium",
        "description": "Classic North Indian stuffed flatbread paired with probiotic-rich fresh yogurt."
    },

    # LUNCH ITEMS
    {
        "name": "Dal Tadka with Jeera Rice & Salad",
        "name_hindi": "दाल तड़का, जीरा राइस",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl dal + 1 cup rice + salad",
        "serving_weight_g": 350,
        "calories": 420,
        "protein_g": 14.0,
        "carbs_g": 68.0,
        "fat_g": 10.0,
        "fiber_g": 7.5,
        "approx_cost_inr": 65.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["yellow arhar dal", "basmati rice", "ghee", "cumin seeds", "garlic", "cucumber"],
        "allergens": ["lactose"],
        "glycemic_index": "Medium",
        "description": "Comforting yellow lentil curry tempered with garlic ghee served with cumin basmati."
    },
    {
        "name": "Rajma Chawal with Cucumber Salad",
        "name_hindi": "राजमा चावल",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl rajma + 1 cup rice",
        "serving_weight_g": 380,
        "calories": 460,
        "protein_g": 16.5,
        "carbs_g": 76.0,
        "fat_g": 9.0,
        "fiber_g": 9.5,
        "approx_cost_inr": 70.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["red kidney beans", "basmati rice", "onion tomato gravy", "ginger", "spices"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Hearty red kidney bean curry cooked in gravy served with steamed white rice."
    },
    {
        "name": "Paneer Butter Masala with 2 Roti",
        "name_hindi": "पनीर बटर मसाला और रोटी",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl paneer + 2 rotis",
        "serving_weight_g": 320,
        "calories": 540,
        "protein_g": 22.0,
        "carbs_g": 48.0,
        "fat_g": 28.0,
        "fiber_g": 6.0,
        "approx_cost_inr": 110.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["paneer", "whole wheat flour", "tomatoes", "cashews", "butter", "cream"],
        "allergens": ["lactose", "nuts", "gluten"],
        "glycemic_index": "Medium",
        "description": "Rich cottage cheese in creamy tomato masala paired with whole wheat phulkas."
    },
    {
        "name": "Chicken Curry with Steamed Rice",
        "name_hindi": "चिकन करी और चावल",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "1 bowl chicken + 1 cup rice",
        "serving_weight_g": 360,
        "calories": 510,
        "protein_g": 34.0,
        "carbs_g": 52.0,
        "fat_g": 16.0,
        "fiber_g": 3.0,
        "approx_cost_inr": 130.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["chicken breast", "rice", "onion", "garlic", "mustard oil", "coriander"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Lean chicken pieces simmered in spicy onion gravy with fragrant rice."
    },
    {
        "name": "Fish Curry with Rice (Bengali Style)",
        "name_hindi": "माछेर झोल और भात",
        "category": "lunch",
        "cuisine": "East Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "1 bowl fish + 1 cup rice",
        "serving_weight_g": 350,
        "calories": 430,
        "protein_g": 28.0,
        "carbs_g": 50.0,
        "fat_g": 12.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 140.0,
        "region": "East India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["rohu fish", "rice", "mustard paste", "turmeric", "nigella seeds", "potato"],
        "allergens": ["fish"],
        "glycemic_index": "Medium",
        "description": "Traditional Bengali fish light broth curry cooked with mustard oil and turmeric."
    },
    {
        "name": "South Indian Meals (Rice, Sambhar, Rasam, Poriyal)",
        "name_hindi": "साउथ इंडियन थाली",
        "category": "lunch",
        "cuisine": "South Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 plate thali",
        "serving_weight_g": 420,
        "calories": 480,
        "protein_g": 13.5,
        "carbs_g": 85.0,
        "fat_g": 9.0,
        "fiber_g": 8.0,
        "approx_cost_inr": 80.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["boiled rice", "toor dal sambhar", "pepper rasam", "cabbage poriyal", "curd"],
        "allergens": ["lactose"],
        "glycemic_index": "Medium",
        "description": "Wholesome South Indian platter featuring digestion-boosting rasam, vegetable sambar, and poriyal."
    },
    {
        "name": "Chole Bhature",
        "name_hindi": "छोले भटूरे",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl chole + 2 bhature",
        "serving_weight_g": 380,
        "calories": 680,
        "protein_g": 18.0,
        "carbs_g": 88.0,
        "fat_g": 28.0,
        "fiber_g": 9.0,
        "approx_cost_inr": 90.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["chana (chickpeas)", "maida flour", "oil", "tea decoction", "amchur", "ghee"],
        "allergens": ["gluten", "lactose"],
        "glycemic_index": "High",
        "description": "Punjabi spicy chickpea curry accompanied by deep-fried refined flour bread."
    },
    {
        "name": "Palak Paneer with 2 Bajra Roti",
        "name_hindi": "पालक पनीर और बाजरा रोटी",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl palak paneer + 2 bajra rotis",
        "serving_weight_g": 340,
        "calories": 440,
        "protein_g": 21.5,
        "carbs_g": 42.0,
        "fat_g": 20.0,
        "fiber_g": 8.5,
        "approx_cost_inr": 85.0,
        "region": "North India",
        "seasonal_months": [10,11,12,1,2,3], # Winter seasonal
        "ingredients": ["spinach puree", "cottage cheese", "millet flour", "garlic", "spices"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Iron-rich spinach puree with soft paneer cubes paired with gluten-free pearl millet rotis."
    },
    {
        "name": "Egg Curry with 2 Wheat Roti",
        "name_hindi": "अंडा करी और रोटी",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "eggetarian",
        "serving_unit": "2 boiled eggs curry + 2 rotis",
        "serving_weight_g": 300,
        "calories": 390,
        "protein_g": 20.0,
        "carbs_g": 34.0,
        "fat_g": 18.0,
        "fiber_g": 4.5,
        "approx_cost_inr": 60.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["boiled eggs", "whole wheat flour", "tomatoes", "onions", "garlic", "spices"],
        "allergens": ["egg", "gluten"],
        "glycemic_index": "Low",
        "description": "Hard-boiled eggs simmered in onion-tomato gravy accompanied by warm whole wheat flatbreads."
    },
    {
        "name": "Soy Chunks Masala Curry with Rice",
        "name_hindi": "सोया बड़ी और चावल",
        "category": "lunch",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl soy curry + 1 cup rice",
        "serving_weight_g": 340,
        "calories": 410,
        "protein_g": 29.0,
        "carbs_g": 54.0,
        "fat_g": 8.0,
        "fiber_g": 7.0,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["textured soy protein", "steamed rice", "curry powder", "tomato", "ginger"],
        "allergens": ["soy"],
        "glycemic_index": "Low",
        "description": "Budget-friendly ultra-high protein soy nuggets cooked in spicy North Indian masala."
    },

    # SNACK ITEMS
    {
        "name": "Roasted Chana & Almond Mix",
        "name_hindi": "भुना चना और बादाम",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 small bowl (50g)",
        "serving_weight_g": 50,
        "calories": 210,
        "protein_g": 9.5,
        "carbs_g": 22.0,
        "fat_g": 9.0,
        "fiber_g": 6.0,
        "approx_cost_inr": 25.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["roasted Bengal gram", "raw almonds", "rock salt", "black pepper"],
        "allergens": ["nuts"],
        "glycemic_index": "Low",
        "description": "Crunchy roasted chickpeas and raw almonds seasoned with Himalayan pink salt."
    },
    {
        "name": "Spiced Masala Buttermilk (Chaas)",
        "name_hindi": "मसाला छाछ",
        "category": "snack",
        "cuisine": "West Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 large glass (300ml)",
        "serving_weight_g": 300,
        "calories": 60,
        "protein_g": 3.5,
        "carbs_g": 4.5,
        "fat_g": 2.5,
        "fiber_g": 0.5,
        "approx_cost_inr": 15.0,
        "region": "All India",
        "seasonal_months": [3,4,5,6,7,8,9], # Summer refreshment
        "ingredients": ["churned yogurt", "water", "roasted cumin", "mint", "black salt"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Cooling probiotic digestive drink infused with mint leaves, ginger, and roasted cumin."
    },
    {
        "name": "Dhokla (3 Pcs)",
        "name_hindi": "ढोकला",
        "category": "snack",
        "cuisine": "West Indian",
        "dietary_type": "vegan",
        "serving_unit": "3 pieces",
        "serving_weight_g": 150,
        "calories": 160,
        "protein_g": 6.0,
        "carbs_g": 26.0,
        "fat_g": 3.5,
        "fiber_g": 3.0,
        "approx_cost_inr": 35.0,
        "region": "West India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["besan (gram flour)", "enokitake", "mustard temper", "curry leaves", "green chili"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Steamed fluffy savory cake made from fermented chickpea batter with mustard tempering."
    },
    {
        "name": "Peanut Sundal / Chat",
        "name_hindi": "मूंगफली सुंडल",
        "category": "snack",
        "cuisine": "South Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl (120g)",
        "serving_weight_g": 120,
        "calories": 230,
        "protein_g": 10.0,
        "carbs_g": 18.0,
        "fat_g": 14.0,
        "fiber_g": 5.5,
        "approx_cost_inr": 20.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["boiled peanuts", "grated coconut", "mustard seeds", "red chili", "curry leaves"],
        "allergens": ["peanuts"],
        "glycemic_index": "Low",
        "description": "Protein-packed tempered boiled peanuts garnished with fresh shredded coconut."
    },
    {
        "name": "Makhana Roasted in Ghee (Fox Nuts)",
        "name_hindi": "मखाना",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl (40g)",
        "serving_weight_g": 40,
        "calories": 150,
        "protein_g": 4.5,
        "carbs_g": 24.0,
        "fat_g": 4.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 40.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["popped lotus seeds", "desi ghee", "rock salt", "black pepper"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Light crunchy lotus seeds roasted in clarification butter with black pepper."
    },
    {
        "name": "Mixed Fresh Fruit Salad",
        "name_hindi": "फ्रूट चाट",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl (200g)",
        "serving_weight_g": 200,
        "calories": 110,
        "protein_g": 1.5,
        "carbs_g": 26.0,
        "fat_g": 0.4,
        "fiber_g": 4.0,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["apple", "papaya", "guava", "pomegranate", "chaat masala"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Refreshing bowl of seasonal Indian fruits sprinkled with digestive spices."
    },

    # DINNER ITEMS
    {
        "name": "Mixed Vegetable Khichdi with Curd",
        "name_hindi": "वेजी खिचड़ी और दही",
        "category": "dinner",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 large bowl khichdi + 1/2 cup curd",
        "serving_weight_g": 350,
        "calories": 340,
        "protein_g": 12.0,
        "carbs_g": 54.0,
        "fat_g": 8.0,
        "fiber_g": 6.5,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["rice", "yellow moong dal", "peas", "carrots", "ghee", "curd", "hing"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Ultimate Indian comfort meal made of rice and mung lentils simmered with vegetables."
    },
    {
        "name": "Grilled Tofu Tikka with Mint Chutney",
        "name_hindi": "टोफू टिक्का",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "6 tikka pieces + salad",
        "serving_weight_g": 220,
        "calories": 290,
        "protein_g": 24.0,
        "carbs_g": 12.0,
        "fat_g": 16.0,
        "fiber_g": 4.0,
        "approx_cost_inr": 90.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["firm tofu", "bell peppers", "lemon", "mustard oil", "tikka spices", "mint"],
        "allergens": ["soy"],
        "glycemic_index": "Low",
        "description": "Tandoori marinated plant-protein tofu skewers charred with capsicum and onions."
    },
    {
        "name": "Tandoori Chicken Breast with Salad",
        "name_hindi": "तंदूरी चिकन और सलाद",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "150g chicken breast + green salad",
        "serving_weight_g": 250,
        "calories": 320,
        "protein_g": 42.0,
        "carbs_g": 6.0,
        "fat_g": 14.0,
        "fiber_g": 2.5,
        "approx_cost_inr": 120.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["boneless chicken breast", "hung curd", "kashmiri chili", "lemon juice", "cucumber"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Lean high-protein tandoori roasted chicken breast served with crunchy garden cucumber salad."
    },
    {
        "name": "Lauki (Bottle Gourd) Sabzi with 2 Jowar Roti",
        "name_hindi": "लौकी सब्ज़ी और ज्वार रोटी",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl lauki + 2 jowar rotis",
        "serving_weight_g": 300,
        "calories": 260,
        "protein_g": 7.5,
        "carbs_g": 48.0,
        "fat_g": 4.5,
        "fiber_g": 8.0,
        "approx_cost_inr": 35.0,
        "region": "All India",
        "seasonal_months": [4,5,6,7,8,9], # Summer vegetable
        "ingredients": ["bottle gourd", "sorghum flour", "cumin", "tomato", "green chili"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Light easily-digestible bottle gourd curry served with gluten-free sorghum grain rotis."
    },
    {
        "name": "Paneer Tikka Salad",
        "name_hindi": "पनीर टिक्का सलाद",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 large salad bowl",
        "serving_weight_g": 240,
        "calories": 360,
        "protein_g": 20.0,
        "carbs_g": 14.0,
        "fat_g": 25.0,
        "fiber_g": 4.5,
        "approx_cost_inr": 95.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["cottage cheese", "capsicum", "onion", "olive oil", "hung curd", "chaat masala"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Char-grilled spiced paneer cubes tossed with crisp bell peppers, tomatoes, and herbs."
    },
    {
        "name": "Millet & Mixed Sprouts Soup",
        "name_hindi": "मिलेट स्प्राउट्स सूप",
        "category": "dinner",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 large bowl",
        "serving_weight_g": 300,
        "calories": 220,
        "protein_g": 11.5,
        "carbs_g": 38.0,
        "fat_g": 3.0,
        "fiber_g": 7.5,
        "approx_cost_inr": 40.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["foxtail millet", "sprouted moong", "carrots", "spinach", "black pepper", "garlic"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Warm immunity-boosting soup made with ancient millets, lentil sprouts, and fresh garlic."
    },
    {
        "name": "Egg White Omelette with Stir-Fried Veggies",
        "name_hindi": "एग व्हाइट ऑमलेट",
        "category": "dinner",
        "cuisine": "Pan-Indian",
        "dietary_type": "eggetarian",
        "serving_unit": "3 egg whites + 1 cup veggies",
        "serving_weight_g": 220,
        "calories": 190,
        "protein_g": 22.0,
        "carbs_g": 10.0,
        "fat_g": 4.5,
        "fiber_g": 3.5,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["egg whites", "bell pepper", "mushroom", "olive oil", "black pepper"],
        "allergens": ["egg"],
        "glycemic_index": "Low",
        "description": "Ultra low-fat high-protein egg white fluff paired with pan-roasted garden mushrooms and peppers."
    },
    {
        "name": "Bhindi Masala (Okra) with 2 Roti",
        "name_hindi": "भिंडी मसाला और रोटी",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl bhindi + 2 rotis",
        "serving_weight_g": 280,
        "calories": 310,
        "protein_g": 8.0,
        "carbs_g": 50.0,
        "fat_g": 9.0,
        "fiber_g": 7.0,
        "approx_cost_inr": 45.0,
        "region": "All India",
        "seasonal_months": [3,4,5,6,7,8,9,10],
        "ingredients": ["okra (bhindi)", "whole wheat flour", "amchur powder", "onion", "mustard oil"],
        "allergens": ["gluten"],
        "glycemic_index": "Low",
        "description": "Stir-fried tangy ladyfinger curry seasoned with dry mango powder served with soft rotis."
    },

    # ─────────── ADDITIONAL LUNCH ITEMS ───────────
    {
        "name": "Methi Thepla with Curd & Pickle",
        "name_hindi": "मेथी थेपला और दही",
        "category": "lunch",
        "cuisine": "West Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "3 theplas + 1/2 cup curd",
        "serving_weight_g": 280,
        "calories": 390,
        "protein_g": 13.0,
        "carbs_g": 52.0,
        "fat_g": 14.0,
        "fiber_g": 6.0,
        "approx_cost_inr": 55.0,
        "region": "West India",
        "seasonal_months": [10,11,12,1,2,3],
        "ingredients": ["fenugreek leaves", "whole wheat flour", "curd", "turmeric", "ajwain"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Low",
        "description": "Thin Gujarati flatbreads loaded with fresh fenugreek leaves served with cooling yogurt."
    },
    {
        "name": "Sambar Rice with Papad",
        "name_hindi": "सांभर राइस और पापड़",
        "category": "lunch",
        "cuisine": "South Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 large bowl",
        "serving_weight_g": 380,
        "calories": 400,
        "protein_g": 12.0,
        "carbs_g": 74.0,
        "fat_g": 7.0,
        "fiber_g": 8.5,
        "approx_cost_inr": 50.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["rice", "toor dal", "drumstick", "tamarind", "mustard seeds", "curry leaves", "papad"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "One-pot comforting South Indian sambar mixed rice with crispy roasted papad."
    },
    {
        "name": "Aloo Gobi Sabzi with 2 Roti",
        "name_hindi": "आलू गोभी और रोटी",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl sabzi + 2 rotis",
        "serving_weight_g": 320,
        "calories": 380,
        "protein_g": 9.0,
        "carbs_g": 60.0,
        "fat_g": 11.0,
        "fiber_g": 7.5,
        "approx_cost_inr": 45.0,
        "region": "North India",
        "seasonal_months": [10,11,12,1,2,3],
        "ingredients": ["potato", "cauliflower", "whole wheat flour", "cumin", "coriander", "turmeric"],
        "allergens": ["gluten"],
        "glycemic_index": "Medium",
        "description": "Dry-tossed potato and cauliflower cooked with cumin and fresh coriander served with soft rotis."
    },
    {
        "name": "Mutton Keema Matar with Laccha Paratha",
        "name_hindi": "मटन कीमा और लच्छा परांठा",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "1 bowl keema + 2 parathas",
        "serving_weight_g": 360,
        "calories": 580,
        "protein_g": 36.0,
        "carbs_g": 42.0,
        "fat_g": 28.0,
        "fiber_g": 5.0,
        "approx_cost_inr": 160.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["minced mutton", "green peas", "onion", "whole wheat flour", "ghee", "ginger garlic"],
        "allergens": ["gluten"],
        "glycemic_index": "Low",
        "description": "Spiced minced lamb cooked with garden peas, aromatic spices, and fresh herbs."
    },
    {
        "name": "Kadhi Chawal with Papad",
        "name_hindi": "कढ़ी चावल",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl kadhi + 1 cup rice + papad",
        "serving_weight_g": 380,
        "calories": 420,
        "protein_g": 10.0,
        "carbs_g": 68.0,
        "fat_g": 11.0,
        "fiber_g": 4.0,
        "approx_cost_inr": 50.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["besan", "curd", "steamed rice", "mustard seeds", "methi seeds", "papad"],
        "allergens": ["lactose"],
        "glycemic_index": "Medium",
        "description": "Tangy gram flour and curd curry with floating pakodas served over steamed white rice."
    },
    {
        "name": "Dal Makhani with Butter Naan",
        "name_hindi": "दाल मखनी और नान",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl dal + 1 naan",
        "serving_weight_g": 350,
        "calories": 550,
        "protein_g": 18.0,
        "carbs_g": 64.0,
        "fat_g": 22.0,
        "fiber_g": 9.0,
        "approx_cost_inr": 120.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["black lentils", "rajma", "butter", "cream", "naan", "garlic"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Medium",
        "description": "Slow-cooked overnight black lentils in butter-cream sauce served with soft tandoor naan."
    },
    {
        "name": "Baingan Bharta with Jowar Roti",
        "name_hindi": "बैंगन भर्ता और ज्वार रोटी",
        "category": "lunch",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl bharta + 2 rotis",
        "serving_weight_g": 300,
        "calories": 310,
        "protein_g": 7.5,
        "carbs_g": 50.0,
        "fat_g": 9.0,
        "fiber_g": 9.0,
        "approx_cost_inr": 40.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["fire-roasted brinjal", "onion", "tomato", "mustard oil", "sorghum flour"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Smoky roasted eggplant mashed with onions and tomatoes served with gluten-free jowar rotis."
    },
    {
        "name": "Prawn Masala with Steamed Rice",
        "name_hindi": "झींगा मसाला और चावल",
        "category": "lunch",
        "cuisine": "Coastal Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "100g prawns + 1 cup rice",
        "serving_weight_g": 330,
        "calories": 390,
        "protein_g": 30.0,
        "carbs_g": 46.0,
        "fat_g": 10.0,
        "fiber_g": 2.5,
        "approx_cost_inr": 150.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["tiger prawns", "coconut milk", "steamed rice", "curry leaves", "kokum"],
        "allergens": ["shellfish"],
        "glycemic_index": "Low",
        "description": "Juicy coconut-based Kerala-style prawns cooked in aromatic spices served with fluffy rice."
    },

    # ─────────── ADDITIONAL SNACK ITEMS ───────────
    {
        "name": "Besan Chilla with Green Chutney",
        "name_hindi": "बेसन चीला",
        "category": "snack",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "2 chillas",
        "serving_weight_g": 160,
        "calories": 230,
        "protein_g": 10.5,
        "carbs_g": 30.0,
        "fat_g": 7.0,
        "fiber_g": 4.5,
        "approx_cost_inr": 25.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["gram flour", "onion", "tomato", "green chili", "coriander", "mint chutney"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Crispy savory gram flour pancakes packed with veggies served with tangy green chutney."
    },
    {
        "name": "Banana & Peanut Butter Smoothie",
        "name_hindi": "केला पीनट बटर स्मूदी",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 large glass (350ml)",
        "serving_weight_g": 350,
        "calories": 310,
        "protein_g": 13.0,
        "carbs_g": 40.0,
        "fat_g": 10.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 50.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["banana", "peanut butter", "milk", "honey", "chia seeds"],
        "allergens": ["peanuts", "lactose"],
        "glycemic_index": "Medium",
        "description": "Thick energy-rich banana and natural peanut butter blended with milk and chia seeds."
    },
    {
        "name": "Paneer Tikka Skewers (4 Pcs)",
        "name_hindi": "पनीर टिक्का",
        "category": "snack",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "4 skewer pieces",
        "serving_weight_g": 150,
        "calories": 240,
        "protein_g": 16.5,
        "carbs_g": 8.0,
        "fat_g": 16.0,
        "fiber_g": 1.5,
        "approx_cost_inr": 80.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["cottage cheese", "capsicum", "hung curd", "tandoori masala", "lemon"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Marinated cottage cheese chunks chargrilled on skewers with colourful peppers."
    },
    {
        "name": "Sprouts Bhel with Tamarind Chutney",
        "name_hindi": "स्प्राउट्स भेल",
        "category": "snack",
        "cuisine": "West Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl (150g)",
        "serving_weight_g": 150,
        "calories": 165,
        "protein_g": 9.0,
        "carbs_g": 28.0,
        "fat_g": 2.0,
        "fiber_g": 7.0,
        "approx_cost_inr": 25.0,
        "region": "West India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["mixed sprouts", "puffed rice", "onion", "tomato", "tamarind chutney", "green chutney"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Mumbai-inspired healthy twist on street bhel using protein-rich sprouts instead of puffed rice."
    },
    {
        "name": "Rajgira Chikki (Amaranth Bar)",
        "name_hindi": "राजगिरा चिक्की",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "2 bars (40g)",
        "serving_weight_g": 40,
        "calories": 175,
        "protein_g": 5.5,
        "carbs_g": 28.0,
        "fat_g": 5.0,
        "fiber_g": 3.0,
        "approx_cost_inr": 20.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["puffed amaranth", "jaggery", "sesame seeds"],
        "allergens": ["sesame"],
        "glycemic_index": "Low",
        "description": "Iron-rich traditional energy bar made with popped amaranth bound with organic jaggery."
    },
    {
        "name": "Green Tea with Roasted Almonds",
        "name_hindi": "ग्रीन टी और बादाम",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 cup tea + 10 almonds",
        "serving_weight_g": 250,
        "calories": 80,
        "protein_g": 3.0,
        "carbs_g": 4.0,
        "fat_g": 5.5,
        "fiber_g": 1.5,
        "approx_cost_inr": 15.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["green tea", "raw almonds", "lemon"],
        "allergens": ["nuts"],
        "glycemic_index": "Low",
        "description": "Antioxidant-rich green tea paired with 10 heart-healthy raw almonds."
    },
    {
        "name": "Corn Chaat with Lemon & Spices",
        "name_hindi": "मकई चाट",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 cup (160g)",
        "serving_weight_g": 160,
        "calories": 160,
        "protein_g": 4.5,
        "carbs_g": 30.0,
        "fat_g": 3.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 30.0,
        "region": "All India",
        "seasonal_months": [7,8,9,10,11],
        "ingredients": ["sweet corn", "lemon juice", "chaat masala", "black salt", "coriander"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Boiled sweet corn kernels tossed with tangy lemon, chaat masala, and fresh coriander."
    },
    {
        "name": "Walnut & Date Energy Balls",
        "name_hindi": "अखरोट और खजूर के लड्डू",
        "category": "snack",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "3 balls (45g)",
        "serving_weight_g": 45,
        "calories": 195,
        "protein_g": 4.0,
        "carbs_g": 22.0,
        "fat_g": 10.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 40.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["medjool dates", "walnuts", "sesame seeds", "cardamom"],
        "allergens": ["nuts"],
        "glycemic_index": "Low",
        "description": "No-bake natural energy bites made from Medjool dates, crunchy walnuts, and cardamom."
    },

    # ─────────── ADDITIONAL DINNER ITEMS ───────────
    {
        "name": "Moong Dal Soup with Garlic Tadka",
        "name_hindi": "मूंग दाल सूप",
        "category": "dinner",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 large bowl (350ml)",
        "serving_weight_g": 350,
        "calories": 200,
        "protein_g": 12.5,
        "carbs_g": 32.0,
        "fat_g": 4.0,
        "fiber_g": 6.0,
        "approx_cost_inr": 30.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["yellow moong dal", "garlic", "cumin seeds", "turmeric", "lemon"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Light detox-friendly moong dal soup finished with crispy garlic and cumin tempering."
    },
    {
        "name": "Masoor Dal with Brown Rice",
        "name_hindi": "मसूर दाल और ब्राउन राइस",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl dal + 3/4 cup rice",
        "serving_weight_g": 320,
        "calories": 360,
        "protein_g": 16.0,
        "carbs_g": 58.0,
        "fat_g": 5.5,
        "fiber_g": 8.0,
        "approx_cost_inr": 40.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["red lentils", "brown rice", "onion", "tomato", "cumin", "coriander"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Iron-rich red lentil dal paired with fiber-dense slow-digesting brown rice."
    },
    {
        "name": "Grilled Fish with Lemon Coriander Sauce",
        "name_hindi": "ग्रिल्ड मछली और चटनी",
        "category": "dinner",
        "cuisine": "Coastal Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "180g fillet + salad",
        "serving_weight_g": 260,
        "calories": 280,
        "protein_g": 35.0,
        "carbs_g": 5.0,
        "fat_g": 12.0,
        "fiber_g": 1.5,
        "approx_cost_inr": 130.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["pomfret/surmai fillet", "lemon", "garlic", "olive oil", "coriander", "spinach salad"],
        "allergens": ["fish"],
        "glycemic_index": "Low",
        "description": "Omega-3 rich Indian fish fillet grilled with garlic, lemon, and coriander sauce."
    },
    {
        "name": "Chicken Tikka with Onion Salad",
        "name_hindi": "चिकन टिक्का और प्याज़ सलाद",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "non_vegetarian",
        "serving_unit": "6 tikka pieces + salad",
        "serving_weight_g": 250,
        "calories": 300,
        "protein_g": 38.0,
        "carbs_g": 6.0,
        "fat_g": 13.0,
        "fiber_g": 2.0,
        "approx_cost_inr": 120.0,
        "region": "North India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["chicken breast", "hung curd", "kashmiri red chili", "lemon", "onion rings"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Classic charcoal-fired chicken pieces marinated in spiced yogurt served with raw onion salad."
    },
    {
        "name": "Tinda (Apple Gourd) Sabzi with Roti",
        "name_hindi": "टिंडा सब्ज़ी और रोटी",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl sabzi + 2 rotis",
        "serving_weight_g": 280,
        "calories": 270,
        "protein_g": 6.5,
        "carbs_g": 45.0,
        "fat_g": 7.5,
        "fiber_g": 7.0,
        "approx_cost_inr": 35.0,
        "region": "North India",
        "seasonal_months": [4,5,6,7,8,9],
        "ingredients": ["apple gourd", "whole wheat flour", "tomato", "cumin", "fennel seeds"],
        "allergens": ["gluten"],
        "glycemic_index": "Low",
        "description": "Light summer squash stir-fry cooked with fennel and cumin served with soft rotis."
    },
    {
        "name": "Paneer Saag (Spinach Cottage Cheese)",
        "name_hindi": "पनीर साग",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl + 2 roti",
        "serving_weight_g": 320,
        "calories": 420,
        "protein_g": 22.0,
        "carbs_g": 36.0,
        "fat_g": 20.0,
        "fiber_g": 7.5,
        "approx_cost_inr": 80.0,
        "region": "North India",
        "seasonal_months": [10,11,12,1,2,3],
        "ingredients": ["mustard saag", "spinach", "cottage cheese", "ghee", "whole wheat roti"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Low",
        "description": "Winter classic slow-cooked mustard greens with soft paneer cubes and desi ghee."
    },
    {
        "name": "Cauliflower & Pea Pulao",
        "name_hindi": "गोभी मटर पुलाव",
        "category": "dinner",
        "cuisine": "North Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl (300g)",
        "serving_weight_g": 300,
        "calories": 320,
        "protein_g": 8.5,
        "carbs_g": 58.0,
        "fat_g": 7.0,
        "fiber_g": 6.5,
        "approx_cost_inr": 55.0,
        "region": "North India",
        "seasonal_months": [10,11,12,1,2,3],
        "ingredients": ["basmati rice", "cauliflower", "green peas", "whole spices", "onion", "mint"],
        "allergens": [],
        "glycemic_index": "Medium",
        "description": "Aromatic one-pot basmati rice cooked with winter vegetables, whole spices, and fresh mint."
    },
    {
        "name": "Tofu & Vegetable Stir-Fry with Millet",
        "name_hindi": "टोफू सब्जी स्टर-फ्राई",
        "category": "dinner",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 plate",
        "serving_weight_g": 300,
        "calories": 290,
        "protein_g": 20.0,
        "carbs_g": 36.0,
        "fat_g": 8.5,
        "fiber_g": 6.0,
        "approx_cost_inr": 75.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["firm tofu", "broccoli", "carrots", "foxtail millet", "soy sauce", "ginger"],
        "allergens": ["soy"],
        "glycemic_index": "Low",
        "description": "High-protein tofu cubes tossed with seasonal vegetables and served on fluffy millet."
    },
    {
        "name": "Tomato Rasam with Steamed Rice",
        "name_hindi": "टमाटर रसम और चावल",
        "category": "dinner",
        "cuisine": "South Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 bowl rasam + 1/2 cup rice",
        "serving_weight_g": 350,
        "calories": 220,
        "protein_g": 5.0,
        "carbs_g": 44.0,
        "fat_g": 3.5,
        "fiber_g": 3.0,
        "approx_cost_inr": 30.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["ripe tomatoes", "toor dal", "black pepper", "cumin", "curry leaves", "steamed rice"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Immunity-boosting South Indian pepper-tomato broth mixed with rice — ideal for light digestion."
    },

    # ─────────── PRE-WORKOUT & POST-WORKOUT ───────────
    {
        "name": "Banana with Peanut Butter (Pre-Workout)",
        "name_hindi": "केला और पीनट बटर",
        "category": "pre_workout",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 banana + 1 tbsp peanut butter",
        "serving_weight_g": 150,
        "calories": 190,
        "protein_g": 6.0,
        "carbs_g": 32.0,
        "fat_g": 5.5,
        "fiber_g": 3.5,
        "approx_cost_inr": 20.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["banana", "peanut butter"],
        "allergens": ["peanuts"],
        "glycemic_index": "Medium",
        "description": "Fast-energy banana paired with natural peanut butter for sustained gym energy."
    },
    {
        "name": "Black Coffee with Dates (Pre-Workout)",
        "name_hindi": "ब्लैक कॉफी और खजूर",
        "category": "pre_workout",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegan",
        "serving_unit": "1 cup coffee + 3 dates",
        "serving_weight_g": 80,
        "calories": 95,
        "protein_g": 1.0,
        "carbs_g": 22.0,
        "fat_g": 0.2,
        "fiber_g": 2.0,
        "approx_cost_inr": 15.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["black coffee", "medjool dates"],
        "allergens": [],
        "glycemic_index": "Low",
        "description": "Metabolism-boosting black coffee with quick-energy natural sugar from dates."
    },
    {
        "name": "Whey Protein Shake with Oats (Post-Workout)",
        "name_hindi": "व्हे प्रोटीन शेक",
        "category": "post_workout",
        "cuisine": "Pan-Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 large glass (400ml)",
        "serving_weight_g": 400,
        "calories": 320,
        "protein_g": 32.0,
        "carbs_g": 38.0,
        "fat_g": 3.5,
        "fiber_g": 4.0,
        "approx_cost_inr": 80.0,
        "region": "All India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["whey protein powder", "rolled oats", "banana", "milk"],
        "allergens": ["lactose", "gluten"],
        "glycemic_index": "Low",
        "description": "High-protein muscle recovery shake blended with oats and banana for glycogen restoration."
    },
    {
        "name": "Curd Rice with Pomegranate (Post-Workout)",
        "name_hindi": "दही चावल और अनार",
        "category": "post_workout",
        "cuisine": "South Indian",
        "dietary_type": "vegetarian",
        "serving_unit": "1 bowl (300g)",
        "serving_weight_g": 300,
        "calories": 310,
        "protein_g": 10.0,
        "carbs_g": 52.0,
        "fat_g": 6.0,
        "fiber_g": 3.5,
        "approx_cost_inr": 40.0,
        "region": "South India",
        "seasonal_months": [1,2,3,4,5,6,7,8,9,10,11,12],
        "ingredients": ["cooked rice", "fresh curd", "pomegranate seeds", "mustard seeds", "curry leaves"],
        "allergens": ["lactose"],
        "glycemic_index": "Low",
        "description": "Probiotic-rich cooling curd rice topped with antioxidant pomegranate for muscle recovery."
    }
]

DEFAULT_SUBSTITUTION_RULES = [
    {"original_food_name": "Paneer Butter Masala with 2 Roti", "substitute_food_name": "Grilled Tofu Tikka with Mint Chutney", "substitute_category": "dinner", "nutritional_match_score": 0.92, "reason": "High protein vegan replacement for cottage cheese."},
    {"original_food_name": "Aloo Paratha with Curd", "substitute_food_name": "Moong Dal Chela (2 Pcs)", "substitute_category": "breakfast", "nutritional_match_score": 0.88, "reason": "Lower carbs and significantly higher protein pancake alternative."},
    {"original_food_name": "Chicken Curry with Steamed Rice", "substitute_food_name": "Soy Chunks Masala Curry with Rice", "substitute_category": "lunch", "nutritional_match_score": 0.94, "reason": "Plant-based high protein match for chicken."},
    {"original_food_name": "Oats Porridge with Almonds & Banana", "substitute_food_name": "Poha with Peanuts & Veggies", "substitute_category": "breakfast", "nutritional_match_score": 0.85, "reason": "Savory Indian warm breakfast alternative for sweet oats."}
]
